version: '3.8'

services:
  nextjs-app:
    image: zenithzjt/personal_navigation_page:${IMAGE_TAG:-latest}
    container_name: personal_navigation_page
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - app_data:/app/data

volumes:
  app_data:   # 声明命名卷